name: Arijit Nandi
title: AI/ML Engineer & Researcher
email: arijit4ai@gmail.com
twitter: "@ArijitN5"
location: Barcelona
country: ES
image: /assets/images/photo.jpg
scholar_id: 4re6DoEAAAAJ
same_as:
  - https://github.com/officialarijit
  - https://www.linkedin.com/in/arin2/
  - https://scholar.google.com/citations?user=4re6DoEAAAAJ
  - https://www.researchgate.net/profile/Arijit-Nandi-2?ev=hdr_xprf
  - https://www.webofscience.com/wos/author/record/AAL-8768-2020
  - https://sciprofiles.com/profile/1338410
  - https://orcid.org/0000-0003-4238-5183
  - https://www.scopus.com/authid/detail.uri?authorId=57220651353
  - https://dblp.org/pid/241/6152.html
