name: Update Publications and Citations

on:
  schedule:
    # Run every day at 6 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch:
    # Allow manual triggering
  push:
    # Run when publications.json is manually updated
    paths:
      - 'data/publications.json'
      - 'scripts/update_publications.py'

jobs:
  update-publications:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run publications update script
      run: |
        cd scripts
        python update_publications.py --auto-update
      env:
        # Add any environment variables if needed
        PYTHONPATH: ${{ github.workspace }}
        
    - name: Check for changes
      id: check-changes
      run: |
        if git diff --quiet data/publications.json; then
          echo "changes=false" >> $GITHUB_OUTPUT
        else
          echo "changes=true" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit and push changes
      if: steps.check-changes.outputs.changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/publications.json
        git commit -m "🤖 Auto-update publications and citations [skip ci]"
        git push
        
    - name: Comment on PR (if triggered by PR)
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '✅ Publications and citations have been automatically updated!'
          }) 